// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eitmpuqpuohvjhfqjpgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpdG1wdXFwdW9odmpoZnFqcGd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2NDYxNzcsImV4cCI6MjA3OTIyMjE3N30.xaPkcC7S7NS0oouqJ9ZjaQIR91tiGO1llb-DbyBlSwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);